### ISSUE TITLE
Please update to remove security risks

### ISSUE THREAD

**Issue by radekBednarik** [skarbala/PotterAPI#25]
Hi, both backend and frontend - lot of 3rd party packages are out-of-date and npm notifies about many security risks.
Since this repo is used by students of your Postman API course, could you please push update?
Best
Radek B.

**Comment by marcel-veselka** [comment]
https://github.com/skarbala/PotterAPI/pull/31

**Comment by marcel-veselka** [comment]
All is set up. This should be closed now.
